<?php

namespace Medical\AnalysisBundle\Repository;

/**
 * laborateryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaborateryRepository extends \Doctrine\ORM\EntityRepository
{
}
